import type { ModelInput, Selection } from './domain'
import { elementDisplayLabel, withEntityDisplayName } from './entityLabels'
import {
  deleteSketchVertex,
  deleteSketchLoop,
  getSketch,
  isSurfaceFamily,
} from './geometrySketch'
import { deleteSection } from './sections'
import { nextPrefixedId, supportNodeId } from './supports'

export function parseSplitPositions(text: string): number[] {
  const tokens = text
    .trim()
    .split(/[,;\s]+/)
    .filter(Boolean)
  if (!tokens.length)
    throw new Error('Enter at least one position, such as 1/2 or 1/4, 3/4.')
  const values = tokens
    .map((token) => {
      const fraction = token.match(/^(\d+(?:\.\d+)?)\/(\d+(?:\.\d+)?)$/)
      const value = fraction
        ? Number(fraction[1]) / Number(fraction[2])
        : Number(token)
      if (!Number.isFinite(value) || value <= 0 || value >= 1)
        throw new Error(
          'Each position must be between 0 and 1, excluding the endpoints.',
        )
      return value
    })
    .sort((a, b) => a - b)
  if (values.length > 100)
    throw new Error('Use at most 100 split positions at a time.')
  if (
    values.some((value, index) => index > 0 && value - values[index - 1] < 1e-9)
  )
    throw new Error('Split positions must be distinct.')
  return values
}

export function splitFrameElement(
  model: ModelInput,
  elementId: string,
  positions: number[],
): ModelInput {
  if (model.model_family !== 'frame')
    throw new Error(
      'Split is available for Frame members. Surface topology is generated by Mesh.',
    )
  const cuts = parseSplitPositions(positions.join(','))
  const element = model.elements.find((item) => item.id === elementId)
  if (!element || element.node_ids.length !== 2)
    throw new Error('Select a two-node member.')
  const start = model.nodes.find((item) => item.id === element.node_ids[0])!
  const end = model.nodes.find((item) => item.id === element.node_ids[1])!
  if (
    !start ||
    !end ||
    Math.hypot(...start.coordinates.map((x, i) => x - end.coordinates[i])) <
      1e-12
  )
    throw new Error('The member must have two distinct endpoint positions.')
  let next = structuredClone(model)
  const nodeIds = [start.id]
  cuts.forEach((fraction) => {
    const coordinates = start.coordinates.map(
      (value, axis) => value + fraction * (end.coordinates[axis] - value),
    )
    const existing = next.nodes.find(
      (node) =>
        Math.hypot(
          ...coordinates.map((value, axis) => value - node.coordinates[axis]),
        ) < 1e-10,
    )
    const id =
      existing?.id ??
      nextPrefixedId(
        'N',
        next.nodes.map((node) => node.id),
      )
    if (!existing) next.nodes.push({ id, coordinates })
    nodeIds.push(id)
  })
  nodeIds.push(end.id)
  const segments = nodeIds.slice(0, -1).map((id, index) => {
    const segmentId =
      index === 0
        ? elementId
        : nextPrefixedId(
            'E',
            next.elements.map((item) => item.id),
          )
    const segment = {
      ...structuredClone(element),
      id: segmentId,
      node_ids: [id, nodeIds[index + 1]],
    }
    if (index > 0) next.elements.push(segment)
    else
      next.elements = next.elements.map((item) =>
        item.id === elementId ? segment : item,
      )
    return segment
  })
  const boundaries = [0, ...cuts, 1]
  // Keep intensity, pattern and scale. Interpolate trapezoidal end intensities on each child.
  const originalLoads = model.loads.filter(
    (load) => load.element_id === elementId,
  )
  if (originalLoads.some((load) => load.kind !== 'element'))
    throw new Error(
      'This member has an unsupported attached load; resolve it before splitting.',
    )
  originalLoads.forEach((load) => {
    segments.forEach((segment, index) => {
      const child = structuredClone(load)
      child.element_id = segment.id
      child.id =
        index === 0
          ? load.id
          : nextPrefixedId(
              'L',
              next.loads.map((item) => item.id),
            )
      for (const axis of ['qx', 'qy']) {
        const a = load.components[`${axis}_i`] ?? 0
        const b = load.components[`${axis}_j`] ?? a
        child.components[`${axis}_i`] = a + (b - a) * boundaries[index]
        child.components[`${axis}_j`] = a + (b - a) * boundaries[index + 1]
      }
      if (index === 0)
        next.loads = next.loads.map((item) =>
          item.id === load.id ? child : item,
        )
      else next.loads.push(child)
    })
  })
  segments.forEach((segment, index) => {
    next = withEntityDisplayName(
      next,
      'elements',
      segment.id,
      `${elementDisplayLabel(model, elementId)} / ${index + 1}`,
    )
  })
  return next
}

export function deleteSelection(
  model: ModelInput,
  selection: Selection,
): ModelInput {
  const { kind, id } = selection
  if (!id || kind === 'model' || kind === 'mesh')
    throw new Error('Select a model item to delete.')
  if (kind === 'sections') return deleteSection(model, id)
  if (kind === 'geometry') {
    const next = getSketch(model).loops.some(
      (loop) => loop.id === id && loop.kind === 'hole',
    )
      ? deleteSketchLoop(model, id)
      : deleteSketchVertex(model, id)
    if (next === model)
      throw new Error('The outer boundary needs at least three vertices.')
    return next
  }
  if (isSurfaceFamily(model) && (kind === 'nodes' || kind === 'elements'))
    throw new Error(
      'Edit the surface geometry and regenerate the mesh to change its topology.',
    )
  const next = structuredClone(model)
  if (kind === 'constraints') {
    const nodeId = supportNodeId(model, id)
    next.constraints = next.constraints.filter(
      (item) => item.node_id !== nodeId,
    )
  } else if (kind === 'materials') {
    if (next.elements.some((element) => element.material_id === id))
      throw new Error(
        'Assign the elements to another material before deleting this material.',
      )
    next.materials = next.materials.filter((item) => item.id !== id)
  } else if (kind === 'loads')
    next.loads = next.loads.filter((item) => item.id !== id)
  else {
    if (kind === 'nodes') {
      if (next.elements.some((element) => element.node_ids.includes(id)))
        throw new Error('Delete connected elements before deleting this node.')
      if (next.analysis.displacement_control?.target.node_id === id)
        throw new Error(
          'Change the displacement-control node before deleting this node.',
        )
      next.nodes = next.nodes.filter((item) => item.id !== id)
      next.constraints = next.constraints.filter((item) => item.node_id !== id)
      next.loads = next.loads.filter((item) => item.node_id !== id)
    } else {
      next.elements = next.elements.filter((item) => item.id !== id)
      next.loads = next.loads.filter((item) => item.element_id !== id)
    }
  }
  return next
}
