"""Generate TypeScript wire types and JSON routes from the checked-in OpenAPI.

No extra build dependency. Unsupported schema shapes fail generation; numerical
ranges and model invariants remain runtime responsibilities of the Python models.
Run after generate_openapi.py; CI uses --check to reject contract drift.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "schemas/openapi-1.0.0.json"
OUTPUT = ROOT / "frontend/src/generated/api.ts"


def literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def ts_type(schema: Any) -> str:
    if schema is True or schema == {}:
        return "unknown"
    if schema is False:
        return "never"
    if set(schema) <= {"title", "description", "default", "examples"}:
        return "unknown"
    if "$ref" in schema:
        prefix = "#/components/schemas/"
        if not schema["$ref"].startswith(prefix):
            raise ValueError(f"Unsupported reference: {schema['$ref']}")
        return f"ApiSchemas[{literal(schema['$ref'][len(prefix) :])}]"
    if "const" in schema:
        return literal(schema["const"])
    if "enum" in schema:
        return " | ".join(map(literal, schema["enum"]))
    for key, separator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
        if key in schema:
            return separator.join(f"({ts_type(item)})" for item in schema[key])
    kind = schema.get("type")
    if kind in ("string", "boolean", "null"):
        return kind
    if kind in ("number", "integer"):
        return "number"
    if kind == "array":
        if "prefixItems" in schema:
            items = schema["prefixItems"]
            if schema.get("minItems") != len(items) or schema.get("maxItems") != len(items):
                raise ValueError("Only fixed-length prefixItems are supported")
            return "[" + ", ".join(ts_type(item) for item in items) + "]"
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object":
        required = set(schema.get("required", []))
        properties = [
            f"{literal(name)}{'' if name in required else '?'}: {ts_type(value)}"
            for name, value in sorted(schema.get("properties", {}).items())
        ]
        additional = schema.get("additionalProperties", True)
        if additional is not False:
            if properties and additional is not True:
                raise ValueError(
                    "Typed additionalProperties with named fields need explicit support"
                )
            properties.append(f"[key: string]: {ts_type(additional)}")
        return "{ " + "; ".join(properties) + " }" if properties else "Record<string, never>"
    raise ValueError(f"Unsupported schema: {schema}")


def render(document: dict) -> str:
    lines = [
        "// Generated by scripts/generate_frontend_contracts.py. Do not edit.",
        "// Wire shapes only; the backend owns numerical and referential validation.",
        "export type JsonValue = string | number | boolean | null | JsonValue[] | "
        "{ [key: string]: JsonValue }",
        "export interface ApiSchemas {",
    ]
    for name, schema in sorted(document["components"]["schemas"].items()):
        # Pydantic publishes JsonValue as {}. HTTP JSON still excludes functions,
        # undefined and class instances, and consumers need recursive narrowing.
        value = "JsonValue" if name == "JsonValue" and schema == {} else ts_type(schema)
        lines.append(f"  {literal(name)}: {value}")
    lines += ["}", "", "export interface JsonRoutes {"]
    for path, methods in sorted(document["paths"].items()):
        for method, operation in sorted(methods.items()):
            if method not in {"get", "post", "delete", "put", "patch"}:
                continue
            successes = [
                response
                for status, response in operation["responses"].items()
                if status.startswith("2")
            ]
            if len(successes) != 1:
                raise ValueError(f"Expected one success response for {method} {path}")
            content = successes[0].get("content", {})
            if content and "application/json" not in content:
                continue  # Binary plots use their own transport.
            result = ts_type(content["application/json"]["schema"]) if content else "void"
            body = operation.get("requestBody", {}).get("content", {}).get("application/json")
            request = ts_type(body["schema"]) if body else "never"
            lines.append(
                f"  {literal(method.upper() + ' ' + path)}: "
                f"{{ request: {request}; response: {result} }}"
            )
    lines += [
        "}",
        "",
        "/** Editor documents explicitly materialize API defaults, including nested fields. */",
        "export type WithDefaults<T> = T extends object",
        "  ? { [K in keyof T]-?: WithDefaults<T[K]> } : T",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(json.loads(SOURCE.read_text()))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit("Frontend contracts are stale. Run generate_frontend_contracts.py.")
        print("Frontend contracts match OpenAPI.")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected)


if __name__ == "__main__":
    main()
